# Site Information
title: "Jekyll Site"
description: "Site Description"
url: "Website URL"

# Repository
repo:
  github_url: 'https://github.com/TangChr/jekyll-template'

author:
  name: "Author Name"
  twitter: "TwitterName"
  twitter: "GitHubName"

# Build
environment: production
baseurl: '/'
permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - serve.cmd
  - vendor

# Other
gems:
  - jekyll-feed
  - jekyll-sitemap